In [65]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [66]:
df=pd.read_csv('train.csv')

In [67]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [68]:
df.shape

(891, 12)

In [69]:
df.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [70]:
num_of_null=df.isnull().sum()
print(num_of_null)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64


In [71]:
df1=df.drop(['Name','Ticket','Fare','PassengerId'],axis='columns')
df1.head()

Survived  Pclass     Sex   Age  SibSp  Parch Cabin Embarked
0         0       3    male  22.0      1      0   NaN        S
1         1       1  female  38.0      1      0   C85        C
2         1       3  female  26.0      0      0   NaN        S
3         1       1  female  35.0      1      0  C123        S
4         0       3    male  35.0      0      0   NaN        S

In [72]:
df2=df1.drop(['Cabin'],axis='columns')

In [73]:
df2.head()

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

In [74]:
df2['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [75]:
df3=df2.replace({'Sex':{'male':1,'female':0},'Embarked':{'S':0,'C':1,'Q':2}})
df3.head()

 

Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    1  22.0      1      0       0.0
1         1       1    0  38.0      1      0       1.0
2         1       3    0  26.0      0      0       0.0
3         1       1    0  35.0      1      0       0.0
4         0       3    1  35.0      0      0       0.0

In [76]:
df3['Pclass'].unique()


array([3, 1, 2], dtype=int64)

In [77]:
df3['SibSp'].unique()


array([1, 0, 3, 4, 2, 5, 8], dtype=int64)

In [78]:

df3['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6], dtype=int64)

In [79]:
print(df3.isnull().sum())

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Embarked      2
dtype: int64


In [80]:
mean_age = df3['Age'].mean()
print(mean_age)

29.69911764705882


In [84]:
df3['Age'].fillna(df3['Age'].mean())
df3.head()

Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    1  22.0      1      0       0.0
1         1       1    0  38.0      1      0       1.0
2         1       3    0  26.0      0      0       0.0
3         1       1    0  35.0      1      0       0.0
4         0       3    1  35.0      0      0       0.0

In [85]:
print(df3.isnull().sum())

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Embarked      2
dtype: int64
